### ISSUE TITLE
Adaptation to Joomla 5

### ISSUE THREAD

**Issue by sgagner** [Valc/jmlocalise#7]
When will Localise be adapted to Joomla 5?
I use the package a lot when creating installation packages and translations for various extensions and for Joomla Core.

**Comment by uzielweb** [comment]
Hello. I am forking this to my account and sending a PR to this team.

**Comment by fontanil** [comment]
@uzielweb 
Hi, did you find how to adapt Localise to J5 ?

**Comment by uzielweb** [comment]
Yes, some time ago, yes. But I need to reanalize it

Em sáb., 8 de jun. de 2024 às 05:43, fontanil ***@***.***>
escreveu:

**Comment by fontanil** [comment]
Thanks uzielweb!
